feat: add a .gitignore when creating a new project
Evaneos/vitaminjs-cli pull request #4
Opened 2017-02-28 11:05 UTC by johangirod

fixes #3

2017-02-28 11:21 UTC, christophehurpeau requested changes

2017-02-28 11:21 UTC, christophehurpeau commented on generators/blank/templates/.gitignore
> +public
/public and /build

because you could have a `build` directory in your src application

2017-02-28 11:21 UTC, christophehurpeau commented on generators/counter/templates/.gitignore
> +public
/public and /build

because you could have a `build` directory in your src application

2017-04-03 14:34 UTC, alepee approved these changes

2017-04-03 14:53 UTC, LucasPerso approved these changes

2017-04-04 15:42 UTC, merged